### ISSUE TITLE
KODI不能播放

### ISSUE THREAD

**Issue by lxg20082008** [kimcrowing/IPTV#1]
IPTV.m3u和IPTV1.m3u不能在KODI里播放，是不是源格式 tvg-id="1" 的原因？

**Comment by kimcrowing** [comment]
> IPTV.m3u和IPTV1.m3u不能在KODI里播放，是不是源格式tvg-id =“ 1”的原因？

是否能看到频道列表？
是：网络问题；否：可以尝试用TeleList转格式
